### ISSUE TITLE
Sieving goes negative with high tier wire meshes

### ISSUE THREAD

**Issue by richardhendricks** [Quantum64/ExGregilo#10]
When using a  high tier wire mesh, the sieve will actually operate backwards.  Level of sieved item goes up outside bounding box of sieve and does not give item.

Occurs with creative mode wire mesh

**Comment by richardhendricks** [comment]
LOL
![2017-12-13_22 34 36](https://user-images.githubusercontent.com/1214811/33975696-d9134fc2-e055-11e7-997f-3ab699144e22.png)

**Comment by Hakameda** [comment]
![muydefmgqbspwx5lvns5qa](https://user-images.githubusercontent.com/1900223/33976221-9cf79c14-e050-11e7-9f25-e3915d5d5efe.png)
With the negative speeds, It actually reverses the direction of sieving. Starting from the bottom then increasing

**Comment by Hakameda** [comment]
![h3-bzkrrtmkotdpv-swfwa](https://user-images.githubusercontent.com/1900223/33976252-d8ecfc64-e050-11e7-8f98-28184c185e04.png)
 It actaully seems to go up forever into the sky lol

**Comment by Quantum64** [comment]
e0f0895eb210ed390b313132026437153849c868

**Comment by Quantum64** [comment]
Fixed
