### ISSUE TITLE
Ex Compressum Support

### ISSUE THREAD

**Issue by Hakameda** [Quantum64/ExGregilo#11]
Lets you sieve compressed gravel, sand etc at a reduced rate. Default is 7 items per 9 gravel instead of 9:9 doing them individually

**Comment by Quantum64** [comment]
I tested with the heavy sieve and it seems to be working fine with the GT outputs. What exactly is the issue?

**Comment by Hakameda** [comment]
didn't work when i tired, will check again

**Comment by Quantum64** [comment]
Ok, reopen if it's still not working for you.
