### ISSUE TITLE
Fortune effect on Meshes

### ISSUE THREAD

**Issue by Hakameda** [Quantum64/ExGregilo#13]
Some meshes can have fortune 1-3 , Does not seem to apply to drop chance or quantity of items

**Comment by Hakameda** [comment]
Perhaps Silk Touch could increase chance of rare items while fortune just effects the quantity per operation

**Comment by jiamingc0824** [comment]
>Perhaps Silk Touch could increase chance of rare items while fortune just effects the quantity per operation

Maybe silk touch u get back the stuff which u can sieve again.
Fortune for increased drop and chance for rare item.

**Comment by Hakameda** [comment]
Silk touch could also just have a small chance to create a full block ore instead of a crushed. Maybe 10% or so

**Comment by Quantum64** [comment]
Added in 96153d254f85f404091041401c1f99512256c019
