### ISSUE TITLE
Issue with Auto Sieve recipe

### ISSUE THREAD

**Issue by WSpadaro** [Quantum64/ExGregilo#15]
I can not craft the auto sieve using a LV Electric Motor I made myself, but if I swap the motor with a LV Electric Motor that I cheated in using NEI the recipe is complete.

Edit: I have done further testing and this also happens with the Conveyor Module, Robot Arm and Piston as well.

![recipe with crafted motor](https://user-images.githubusercontent.com/34498631/33977928-57b1dd84-e06b-11e7-8196-6b44e63f2c6f.PNG)
![recipe with cheated in motor](https://user-images.githubusercontent.com/34498631/33977929-57bfa054-e06b-11e7-8d5e-ed503f70236b.PNG)

**Comment by Hakameda** [comment]
On a side note, Auto-Seive is also broken. If the output becomes full, instead of stopping it voids all current input

**Comment by Quantum64** [comment]
Wow, that makes no sense.

**Comment by Quantum64** [comment]
0389fb1d243cbe1720a14e7fa5fa0b4d4be53bc2

**Comment by Quantum64** [comment]
Can anyone confirm if this is fixed https://github.com/Quantum64/ExGregilo/releases

**Comment by Hakameda** [comment]
i'll reload and try

**Comment by Hakameda** [comment]
Yup its good - http://prntscr.com/hnq2zs

**Comment by Quantum64** [comment]
Awesome
