### ISSUE TITLE
GUI Elements Missing or unable to load

### ISSUE THREAD

**Issue by WSpadaro** [Quantum64/ExGregilo#16]
I have tested the Auto Sieve of varying tiers and they seem to work however, the GUI seems to not be working. They are not loading for the Auto Sieve and Auto Sieve recipes.

![auto sieve recipes](https://user-images.githubusercontent.com/34498631/33978443-c65f78f2-e06d-11e7-81bd-85a163de29d7.PNG)
![auto sieve gui](https://user-images.githubusercontent.com/34498631/33978444-c668abf2-e06d-11e7-9659-c7c487e43312.PNG)

**Comment by Hakameda** [comment]
http://prntscr.com/ho7av6

**Comment by Quantum64** [comment]
Fixed in c9ec702b9b071ed7447a3bbb2525825438fe4e73
