### ISSUE TITLE
Auto Sieve Different Output than Advanced Sieve

### ISSUE THREAD

**Issue by WSpadaro** [Quantum64/ExGregilo#17]
From playing around with the auto sieve and the advanced sieve, I have noticed that the advanced sieve outputs only gregtech related items (This is ideal); however, the auto sieve outputs Ex-Nihilo Items such as the Broken Ores. I'm unsure if this is intended or not but I would assume not since the advanced sieve doesn't.

**Comment by Quantum64** [comment]
1b6fdc79acb9a6cb1e6f5ebee9def81a4b58b4f0 should fix it

**Comment by WSpadaro** [comment]
Did you change the id's by any chance? Also, I'll test it tomorrow after work.

**Comment by Quantum64** [comment]
It theoretically detects if the NH version is being used and if it is shifts up ids by 10000.

**Comment by WSpadaro** [comment]
Alright, I'll test tomorrow and let you know!

**Comment by Hakameda** [comment]
This is also fixed now in the latest release, Only further suggestion would probably be to remove lapis, coal and apatite in favor of crushed variants

**Comment by Quantum64** [comment]
7bc34e231f351767735b66d3d1f99482bdad5b08

**Comment by Hakameda** [comment]
It seems i was wrong, This is the output from an UV Sieve. Seemed okay when i tested LV but maybe i didn't process enough - http://prntscr.com/ho5ohf

**Comment by Quantum64** [comment]
Can you try this again?

**Comment by WSpadaro** [comment]
Problem seems to be fixed. This is the output from an UV Sieve, 5 Stacks of Gravel and 3 of Sand
![auto sieve output](https://user-images.githubusercontent.com/34498631/34075082-e1e31c96-e289-11e7-8067-46467d748c3d.PNG)
