### ISSUE TITLE
Config

### ISSUE THREAD

**Issue by Hakameda** [Quantum64/ExGregilo#18]
Is it possible to specify what drops we could get via config? Something similar to ex nihilo. If its too big a pain in the ass, Don't worry about it. Can just minetweak it

**Comment by Quantum64** [comment]
Right now (and for the foreseeable future) the only way to change auto sieve drops will be minetweaker.

If you have any ideas for making the drops more fair, they are set in the code here: https://github.com/Quantum64/ExGregilo/blob/master/src/main/java/co/q64/exgregilo/link/gregtech/GregTech.java#L89

**Comment by Hakameda** [comment]
They seem okay, Our only reason to tweak is to use them for gtnh progression. A comma separated list would prob have been a bit faster but its all good. Can just minetweak em
