### ISSUE TITLE
Auto Sieve Does not Support Input from Pipes

### ISSUE THREAD

**Issue by WSpadaro** [Quantum64/ExGregilo#21]
The Auto Sieve does not seem to support having items piped into it. I have tested this with gregtech pipes as well as with vanilla minecraft hoppers. Neither were able to input sand from top or sides. I tried screwdriving the machine to change input from output side allowed as well. 
![no input](https://user-images.githubusercontent.com/34498631/34075101-603c5382-e28a-11e7-8650-c20b088e7db9.PNG)

**Comment by Hakameda** [comment]
Thats odd, It had worked for me with a transfer node

**Comment by WSpadaro** [comment]
I just tried a transfer node and it doesn't seem to be working. What side were you inputting to?
![transfer node](https://user-images.githubusercontent.com/34498631/34075339-1d5dec4e-e292-11e7-99f6-dcf2bd0fa795.PNG)

**Comment by Hakameda** [comment]
Are you inputting to the output of the machine? Try using a screwdriver on it to allow input from output side

**Comment by Hakameda** [comment]
http://prntscr.com/hohjsn @WSpadaro

**Comment by WSpadaro** [comment]
I'm not inputting to the output of the machine. I am inputting to multiple sides at once, so they can't both be the output. I'll have to do further testing.

**Comment by WSpadaro** [comment]
I have found out that I can input into the LV Auto Sieve. 

I have retest every Auto Sieve and I can now input into them all the same way I was unable to before. I'm not sure what caused the original bug but since it is unreplicatable, I think this should be closed and if it happens again, I'll work on recreating it.

**Comment by WSpadaro** [comment]
Ok, I had this problem again... I can't pinpoint why it happens

**Comment by WSpadaro** [comment]
Alright so I figured out the bug, The problem is, you can auto input Gravel into the Auto Sieve but you can not pipe in Sand.

**Comment by Quantum64** [comment]
interesting

**Comment by Quantum64** [comment]
Try with 4e5e8b7c9890d2a6059edae2522ebd6384f62a95 once it's done building

**Comment by WSpadaro** [comment]
Can confirm that Sand can now be piped into the Auto Sieve.
