### ISSUE TITLE
Auto-Sieve unexpected sieve outputs

### ISSUE THREAD

**Issue by ghost** [Quantum64/ExGregilo#3]
When using the Electric Auto Sieve, it is ignoring the Ex Nihilo sieve registry and using its (i assume) own hard coded values.

Please adjust this so that when you make changes with Minetweaker to the sieve, it carries over to GT's sieves and uses the ExN registry instead.

**Comment by Quantum64** [comment]
Since the auto sieve and the regular sieve give different outputs, it wouldn't be using the normal values from the sieve registry anyway.  I can probably add minetweaker support if that's what you're after.

**Comment by ghost** [comment]
MineTweaker support would be super duper awesome for further tweaking enhancement 👍

**Comment by ghost** [comment]
So how about that Minetweaker support :P

**Comment by Quantum64** [comment]
School and my job have really pushed this project aside... in fact I completely forget it existed until I got this email notification.  Unfortunately, I probably won't be working on it any time soon, but it would be great if another programmer could contribute to it.

**Comment by Quantum64** [comment]
Done 8d2b2f190ff4126254fb3ad042f62106896b454d
