### ISSUE TITLE
Basic Sieve + Flint Mesh

### ISSUE THREAD

**Issue by Hakameda** [Quantum64/ExGregilo#36]
Basic Sieve with its current recipe would require tools, which would need a sieve to get. Flint mesh is only 1 use. To replace the ex nihilo sieve it would probably need a diff recipe if that's intended to be the first thing you use

**Comment by Quantum64** [comment]
Maybe I can enable wooden GT tools somehow. Also I don't think we can use flint as a mesh material because GT does not provide a durability for it and I can't modify that value myself.

**Comment by Quantum64** [comment]
74fa9df6704b6d6dbce319c7e18c6beff342f924 no tools required
