### ISSUE TITLE
Hammer Recipes

### ISSUE THREAD

**Issue by ghost** [Quantum64/ExGregilo#4]
Currently, ExG does not provide an "auto hammer" to complement the auto sieve.
The existing Forge Hammer is a great solution for this.

Cobblestone -> Gravel already exists for both, at 10 EU/t for 16 ticks totalling 160 EU (and equivalent steam energy requirement)
Gravel -> Sand does not exist.
Sand -> Dust does not exist.

By default, ExNihilo has all 4 of these materials at the same tier, no difference in sifting time or hammering time. So, adding Gravel->Sand & Sand->Dust at 10EU/t for 16 ticks (160EU) to the Forge Hammer seems like an okay thing to do.

Upside: Saves you having to code a brand new block and tile entity and set of recipes and machine handler 😆 👍

**Comment by Quantum64** [comment]
Yes, I can do that, or better yet if you want to PR the code that would be super awesome, I'm sort of crushed for time until December 17, so I might not get a chance to work on this side project until then.

**Comment by Quantum64** [comment]
Looks like Gravel -> Sand already exists in the forge hammer, I'll add Sand -> Dust now.

**Comment by Quantum64** [comment]
Fixed in  0e950a4ec87ad21150576d9ded3815fccfd5d7ba
