### ISSUE TITLE
Restarting! Woohoo!

### ISSUE THREAD

**Issue by richardhendricks** [Quantum64/ExGregilo#7]
Just wanted to check and see if this project is no longer under development. Thanks.

**Comment by Quantum64** [comment]
I haven't had much time to work on it lately (wow it's been an entire year)...

**Comment by richardhendricks** [comment]
Thanks for commenting.  Would you accept PRs?

**Comment by Quantum64** [comment]
Sure, that would be awesome!

**Comment by Quantum64** [comment]
I'm not exactly sure what has changed in GT5U's API that needs to be updated here for the mod to function, but I'm sure some changes will need to be made just to get it to build.

**Comment by Quantum64** [comment]
Oh a few other things I remembered:

Advanced sieve should probably be using ITexture for rendering instead of TESR for performance reasons, it would be great if you could figure that out.

There's currently no way to get GT gems, I was thinking I would add an HV era machine that could sift "gem sand" which would be made with a diamond, and emerald, and 2 gravel into a random GT gem with a random quality. Something super hard.

Some people wanted MineTweaker support for my machine recipes.

**Comment by richardhendricks** [comment]
Assume I am a friendly idiot at this point. :D

**Comment by Quantum64** [comment]
Aight, feel free to ask anything.

I actually didn't realize that there was any interest left for this project, I could probably find some time to work on it if people are actually interested in using it.

ITexture is an interface for GregTech's custom rendering system that it uses for pipes, machines, cables, etc... and supposedly it's really fast, but I don't know much about how it works or how to use it. TESRs or TileEntitySpecialRenderers are Minecraft's way of doing fancy rendering, but as far as I understand it's super slow and runs on a single thread, so having a ton of advanced sieves will destroy FPS. This is a problem that the older versions of Ex Nihilo sieves (which my advanced sieve rendering code is based on) also had.

**Comment by richardhendricks** [comment]
We have had some requests in the Gregtech New Horizons discord for a skyblocks version, so there is definitely some interest for the Ex Greglio style mod.

**Comment by Hakameda** [comment]
yeah i asked a long time ago about support for sky block, Some kinda ID conflict but didn't seem to work.

Something to with NH's slightly modded gt5u probably. But also needed some features to make it more inline with how gtnh would be played for skyblock. Like gated ores, Sifting moon dust for titanium kinda stuff

**Comment by BelanaBelow** [comment]
I would love to see Exgregilo in a Greg Tech: New Horizon way. I started some Sky Block maps, but most of my fun is based on Greg. I saw your Mod a few month ago and until now I'm waiting for a skyblock Greg mod. So I wish it will be done in the future :-)

**Comment by Hakameda** [comment]
It would be cool, would need some tweaks to make it fit inside gtnh. But
I'd help do config changes for that

**Comment by Quantum64** [comment]
Alright, I can try to find some time to work on this, but keep in mind that I am very busy with school and other programming work, so progress probably won't be super rapid.

Also I'm not sure how much GT5U's APIs have changed over the past year, so it could take considerable time just to get the mod into a functional state with its current features.

**Comment by Hakameda** [comment]
If you need help or ideas I can help, Only thing is perhaps check both gt5u
jars and gt5u from gtnh. Slightly different sometimes and would need
different configs

**Comment by WSpadaro** [comment]
I am very interested in this as well, I'm willing to add it to my playthrough as soon as its in an even semi-working state.

**Comment by Quantum64** [comment]
It's in a sort of working state right now, you just have to compile it yourself until I decide it's time for a release. I just fixed the recipes for Auto Sieves.

**Comment by WSpadaro** [comment]
Sounds great. I've downloaded the source and now I just have to figure out how to build it.

**Comment by Quantum64** [comment]
[libs.zip](https://github.com/Quantum64/ExGregilo/files/1554187/libs.zip)
You'll want to use those in your libs folder, everything else is provided by gradle. (Hoping to upload those to my maven repo soon too)

**Comment by WSpadaro** [comment]
I'm having an issue with a few dependencies. It says "Could not resolve :Railcraft:1.7.10-9.40.0" as well as two others. Sorry if this is not the place to ask this question.

Edit: It says that peer not authenticated

**Comment by Quantum64** [comment]
The railcraft repository is in the build.gradle file, it should work with
no further configuration assuming your forge workspace is setup correctly.

**Comment by Hakameda** [comment]
You want to upload the jar when your done for noobs like me that can't compile it?

**Comment by Quantum64** [comment]
Here's the railcraft jar http://addons-origin.cursecdn.com/files/2219/321/Railcraft_1.7.10-9.4.0.0.jar

You can find the others on the internet too, just make sure you get the "dev versions" of the mods because they don't have dependency requirements.

Edit: Put them in the libs folder, then remove dependency line from the build.gradle file.

**Comment by WSpadaro** [comment]
Thanks for the help, I have downloaded the three libraries it was looking for (Railcraft, EnderIO, and EE3) now I just have to figure out how to get forge to use local copies instead of going out and looking for them and failing with a "peer not authenticated" failure. Thanks for the help, I'll keep working on it tomorrow. First time using gradle so sorry for the headache.

**Comment by WSpadaro** [comment]
Sorry didn't see your edit. I will do that tomorrow morning. Thanks so much for the help. Can't wait to try it out

**Comment by WSpadaro** [comment]
Alright, I resolved all of the dependency issues I was having. I had to download all of the following dev files and place them in the ./libs folder: EnderIO, EE3, Ex-Astris, Excompressum, gregtech-5.09.31, Railcraft, forestry, and NEI). I have one final error that involves states:
exgregilo\link\gregtech\tools\MetaGeneratedTools.java:19: error: MetaGeneratedTools is not abstract and does not override abstract method used(ItemStack,EntityPlayer,BlockPos) in ITool
Thanks again for all the help

**Comment by richardhendricks** [comment]
Thanks!  Nice to see activity on this again.

**Comment by Quantum64** [comment]
Ok so theoretically with the addition of gem sand the entire GT tech tree should be completable. It would be great if someone could confirm that.

Here's a compiled version of the mod if anyone wants to test it out. 
https://mega.nz/#!I0BDXLAD!6yK8aLLSkMOvKcKKpTeKRInnQ5xx49NukXdpBybLMfo

**Comment by Hakameda** [comment]
Will be testing Tonight then, was it possible to add minetweaker support?

**Comment by Quantum64** [comment]
I added minetweaker support and it should work but I havn't tested it. Right now it supports adding and removing recipes from the auto sieve.

**Comment by Hakameda** [comment]
Probably going to modify it slightly for gtnh. But will test tonight and
let you know

**Comment by Hakameda** [comment]
Do you know offhand if regular sieve recipes can br overridden with
minetweaker or if it can be forced overridden by another mod?

**Comment by WSpadaro** [comment]
I will also test tonight when I get home. Excited to try it out.

**Comment by Hakameda** [comment]
Did you also get nei support working? Says it was an issue opened last year

**Comment by Quantum64** [comment]
Not sure if regular sieves can be overridden by default but if not it's something I might be able to add to this mod since it already has a system in place for editing default sieve registries.

NEI mostly works but it still has the issue where my machines have a missing GUI texture when displaying recipes. I have no idea why.

**Comment by Quantum64** [comment]
Should build out of the box with no libs folder now.

**Comment by richardhendricks** [comment]
@WSpadaro You have to add in the Forestry mod. 
@Quantum64 I needed to populate the libs folder like this

12/13/2017  09:04 PM    <DIR>          .
12/13/2017  09:04 PM    <DIR>          ..
12/13/2017  08:58 PM         4,708,129 EnderIO-1.7.10-2.3.0.429_beta-dev.jar
12/13/2017  08:56 PM           584,539 Ex-Astris-MC1.7.10-1.16-36.jar
12/13/2017  08:56 PM           398,521 excompressum-mc1.7.10-1.1.149.jar
12/13/2017  09:03 PM         3,322,286 forestry_1.7.10-4.2.16.64.jar
12/13/2017  08:56 PM         9,620,063 gregtech-5.09.31-dev.jar
12/13/2017  08:57 PM         3,537,970 Railcraft_1.7.10-9.4.0.0.jar

That's based off your commit of
586d4b8cd3fb9293c52c806b9f046a83f394504a

I had to also remove the enderio line from build.gradle and add in the libraries.

**Comment by richardhendricks** [comment]
There is also an undocumented exnihilo dependency in AdvancedSieveRender

**Comment by Quantum64** [comment]
@richardhendricks What error do you get without the libraries. Everything needed to build is hosted on remote repositories now, so I can build with an empty libs folder.

DId anyone test Minetweaker support? I should be able to address most of the tickets today, although I currently have no idea how to fix the NEI or crafting ones.

**Comment by Hakameda** [comment]
I'll see if i can test minetweaker before work today else it wouldn't be until tonight

**Comment by Hakameda** [comment]
Playing with minetweaker now to see if i can get it working

**Comment by Hakameda** [comment]
Minetweaker does not appear to be working, Can remove other recipes from mc and mods but not exgregilo stuff

**Comment by Quantum64** [comment]
https://github.com/Quantum64/ExGregilo/blob/master/src/main/java/co/q64/exgregilo/link/minetweaker/machines/ZenAutoSieve.java

The minetweaker support is currently only for sieving products (though it should probably work for recipes too). You should be able to use the methods addProduct and removeProduct on mods.exgregilo.AutoSiev

**Comment by Quantum64** [comment]
Each time I make a commit a compiled version of the mod will automatically be posted here: https://github.com/Quantum64/ExGregilo/releases
Should make testing easier.

**Comment by Hakameda** [comment]
Nice. Will keep playing with it

**Comment by Hakameda** [comment]
Looks like a crash after updating to latest - 
[fml-client-latest.log](https://github.com/Quantum64/ExGregilo/files/1561461/fml-client-latest.log)

**Comment by Quantum64** [comment]
It isn't crashing for me. Also that crash doesn't look mod related.

**Comment by Hakameda** [comment]
i'll double check that

Edit: Weird musta been something else

**Comment by richardhendricks** [comment]
Was using ancient version of java and new version of gradle. :D  All is building fine now.

Closing ticket.
