### ISSUE TITLE
Changing ID of machines

### ISSUE THREAD

**Issue by Hakameda** [Quantum64/ExGregilo#9]
I believe this is a result of something specific to gtnh - https://hastebin.com/likumalubi.rb

Anyway we can configure the id's of machines? The config pops up as blank

11264 - 12000 are reserved for Quantum64.
11310 is already occupied!

Edit: Looks like GTNH uses a ton of id's before the reservation took effect. Going to look for a range if its not a big deal to change it

**Comment by richardhendricks** [comment]
Couple of options
- Fix GT:NH ranges.  Not likely to happen since it breaks servers and games in progress
- Move Ex Gregilo to new ranges. A bit unfair, but hasn't been in circulation so probably not fatal.
- Add a kludge in ExG to detect GT:NH and use different ranges when in GT:NH. Ugly.

**Comment by richardhendricks** [comment]
Built this version.  Modified three things:

Set mod name to ModData.MODID so NEI will properly show up as ExGregilo
Moved AutoSieves to start at 13000
Moved GemExtractors to start at 13010
Changed version to 1.1.0-moron

Not for public distribution.


[exgregilo-1.1.0-moron.zip](https://github.com/Quantum64/ExGregilo/files/1557935/exgregilo-1.1.0-moron.zip)

**Comment by Quantum64** [comment]
914ea63e14997b2507500546c6acc1bf688a8b32
